export const leaveBalance = {
  staffID: '81001879',
  totalleaves: '32',
  leaves: {
    data: ['20', '6', '6'],
    unit: ['Privilege Leave(PL)', 'Casual Leave(CL)', 'Sick Leave(SL )'],
    text: '',
  },
  leaveinfo: 'This data was last updated on 01 Mar 2024, 15:36 pm',
};

export const deadHeadLayover = {
  staffID: '81001879',
  crewType: 'cabincrew',
  deadHeadHours: '4',
  totalLayovers: '5',
  intlDomesticLayovers: {
    data: ['1', '2'],
    unit: ['international', 'domestic'],
    text: '',
  },
  deadheadinfo: 'This data is for the month of February 2024',
  layoverinfo: 'This data is for the month of February 2024',
};

export const blockHours = {
  staffID: '81001879',
  totalblockhours: '95',
  blockoursinfo:
    'This data is for 03 Feb 2024 to 01 Mar 2024, last updated on 02 Mar 2024, 09:59 am',
};

export const takeOffsLandings = {
  staffID: '81001879',
  totalperformance: '6',
  takeOffsLandings: {
    data: ['2', '4'],
    unit: ['take offs', 'landings'],
    text: '',
  },
  info: 'This data is for 05 Dec 2023 to 04 Mar 2024, last updated on 05 Mar 2024, 15:11 pm',
};

export const rosterInfo = {
  staffID: '81001879',
  roster: [
    {
      flightNumber: 'AI101',
      travelDate: '2024-05-03 04:22:08',
      source: 'DEL',
      sourceCity: 'Delhi',
      sourceCountry: 'India',
      sourceTime: '2024-03-20T10:40:00.000+00:00',
      destination: 'JFK',
      destinationTime: '2024-03-20T17:15:00.000+00:00',
      destinationCity: 'New York',
      destinationCountry: 'USA',
    },
    {
      flightNumber: 'AI102',
      travelDate: '2024-03-10 04:22:08',
      source: 'JFK',
      sourceCity: 'New York',
      sourceCountry: 'USA',
      sourceTime: '2024-03-22T10:40:00.000+00:00',
      destination: 'DEL',
      destinationTime: '2024-03-22T17:15:00.000+00:00',
      destinationCity: 'Delhi',
      destinationCountry: 'India',
    },
    {
      flightNumber: 'AI103',
      travelDate: '2024-03-10 04:22:08',
      source: 'SFO',
      sourceCity: 'San Francisco',
      sourceCountry: 'USA',
      sourceTime: '2024-04-12T10:40:00.000+00:00',
      destination: 'DEL',
      destinationTime: '2024-04-12T20:15:00.000+00:00',
      destinationCity: 'Delhi',
      destinationCountry: 'India',
    },
    {
      flightNumber: 'AI102',
      travelDate: '2024-03-10 04:22:08',
      source: 'JFK',
      sourceCity: 'New York',
      sourceCountry: 'USA',
      sourceTime: '2024-03-09T11:40:00.000+00:00',
      destination: 'DEL',
      destinationTime: '2024-03-09T19:15:00.000+00:00',
      destinationCity: 'Delhi',
      destinationCountry: 'India',
    },
    {
      flightNumber: 'AI106',
      travelDate: '2024-03-10 04:22:08',
      source: 'JFK',
      sourceCity: 'New York',
      sourceCountry: 'USA',
      sourceTime: '2024-03-31T11:40:00.000+00:00',
      destination: 'DEL',
      destinationTime: '2024-03-31T19:15:00.000+00:00',
      destinationCity: 'Delhi',
      destinationCountry: 'India',
    },
  ],
};

export const docExp = [
  {
    crew_id: '81013162',
    document_type: 'passport',
    sub_document_type: null,
    upload_type: 'arms',
    doc_id: null,
    given_name: 'ARJUN',
    surname: 'AHLUWALIA',
    passport_no: 'V7608416',
    valid_from: null,
    valid_upto: '24-Mar-32',
    issuing_country: null,
    place_of_issue_renewal: null,
    identification_marks: null,
    license_name: null,
    ref_no_pass_no: null,
    issued_date: null,
    cmc_no: null,
    days_to_expire: null,
    instructor_name: null,
    other_details: null,
    visa_no: null,
    visa_type: null,
    date_of_registration: null,
    visa_valid_upto: null,
    visa_valid_countries: null,
    no_of_entry: null,
    flying_license_no: null,
    license_type: null,
    general_date: null,
    vaccination_type: null,
    medical_center: null,
    hospital_name: null,
    date_of_exam: null,
    result: null,
    dr_name: null,
    medical_category: null,
    aviation_authority: null,
    renewed_on: null,
    middle_name: null,
    designation: null,
    team: null,
    emp_no: null,
    blood_grp: null,
    doj: null,
    visible: null,
    expiry_days: '2948',
  },
  {
    crew_id: '81013162',
    document_type: 'aep',
    sub_document_type: null,
    upload_type: 'arms',
    doc_id: null,
    given_name: null,
    surname: null,
    passport_no: null,
    valid_from: null,
    valid_upto: '25-Jun-26',
    issuing_country: null,
    place_of_issue_renewal: null,
    identification_marks: null,
    license_name: 'DEL2301018832',
    ref_no_pass_no: null,
    issued_date: null,
    cmc_no: null,
    days_to_expire: null,
    instructor_name: null,
    other_details: null,
    visa_no: null,
    visa_type: null,
    date_of_registration: null,
    visa_valid_upto: null,
    visa_valid_countries: null,
    no_of_entry: null,
    flying_license_no: null,
    license_type: null,
    general_date: null,
    vaccination_type: null,
    medical_center: null,
    hospital_name: null,
    date_of_exam: null,
    result: null,
    dr_name: null,
    medical_category: null,
    aviation_authority: null,
    renewed_on: null,
    middle_name: null,
    designation: null,
    team: null,
    emp_no: null,
    blood_grp: null,
    doj: null,
    visible: null,
    expiry_days: '849',
  },
  {
    crew_id: '81013162',
    document_type: 'passport',
    sub_document_type: 'passport(India)',
    upload_type: 'db',
    doc_id: '81013162_passport_passport(India)2026823076',
    given_name: 'SIVA SELVA KUMAR',
    surname: null,
    passport_no: 'H 1591116',
    valid_from: null,
    valid_upto: '30-Nov-32',
    issuing_country: 'IND',
    place_of_issue_renewal: null,
    identification_marks: null,
    license_name: null,
    ref_no_pass_no: null,
    issued_date: null,
    cmc_no: null,
    days_to_expire: null,
    instructor_name: null,
    other_details: null,
    visa_no: null,
    visa_type: null,
    date_of_registration: null,
    visa_valid_upto: null,
    visa_valid_countries: null,
    no_of_entry: null,
    flying_license_no: null,
    license_type: null,
    general_date: null,
    vaccination_type: null,
    medical_center: null,
    hospital_name: null,
    date_of_exam: null,
    result: null,
    dr_name: null,
    medical_category: null,
    aviation_authority: null,
    renewed_on: null,
    middle_name: null,
    designation: null,
    team: null,
    emp_no: null,
    blood_grp: null,
    doj: null,
    visible: null,
    expiry_days: '3190',
  },
  {
    crew_id: '81013162',
    document_type: 'visa',
    sub_document_type: 'visa(Usa)',
    upload_type: 'db',
    doc_id: '81013162_visa_visa(Usa)1540902123',
    given_name: null,
    surname: null,
    passport_no: 'Z6725875',
    valid_from: null,
    valid_upto: null,
    issuing_country: 'USA',
    place_of_issue_renewal: null,
    identification_marks: null,
    license_name: null,
    ref_no_pass_no: null,
    issued_date: null,
    cmc_no: null,
    days_to_expire: null,
    instructor_name: null,
    other_details: null,
    visa_no: '20223392980001',
    visa_type: 'C1/D',
    date_of_registration: null,
    visa_valid_upto: '12-Mar-32',
    visa_valid_countries: null,
    no_of_entry: null,
    flying_license_no: null,
    license_type: null,
    general_date: null,
    vaccination_type: null,
    medical_center: null,
    hospital_name: null,
    date_of_exam: null,
    result: null,
    dr_name: null,
    medical_category: null,
    aviation_authority: null,
    renewed_on: null,
    middle_name: null,
    designation: null,
    team: null,
    emp_no: null,
    blood_grp: null,
    doj: null,
    visible: null,
    expiry_days: '90',
  },
  {
    crew_id: '81013162',
    document_type: 'aep',
    sub_document_type: null,
    upload_type: 'db',
    doc_id: '81013162_aep374462101',
    given_name: null,
    surname: null,
    passport_no: null,
    valid_from: null,
    valid_upto: '12-Mar-32',
    issuing_country: null,
    place_of_issue_renewal: null,
    identification_marks: null,
    license_name: 'DEL2000226315',
    ref_no_pass_no: null,
    issued_date: '09/11/2020 ',
    cmc_no: null,
    days_to_expire: null,
    instructor_name: null,
    other_details: null,
    visa_no: null,
    visa_type: null,
    date_of_registration: null,
    visa_valid_upto: null,
    visa_valid_countries: null,
    no_of_entry: null,
    flying_license_no: null,
    license_type: null,
    general_date: null,
    vaccination_type: null,
    medical_center: null,
    hospital_name: null,
    date_of_exam: null,
    result: null,
    dr_name: null,
    medical_category: null,
    aviation_authority: null,
    renewed_on: null,
    middle_name: null,
    designation: null,
    team: null,
    emp_no: null,
    blood_grp: null,
    doj: null,
    visible: null,
    expiry_days: '200',
  },
];

// export const flyingStats = {
//   CPBlockHours: 0,
//   FOBlockHours: 0,
//   TotalBlockHours: 0,
//   FDPHours: 5255,
//   DPHours: 5647,
// };

export const flyingStats = {
  staffID: '80008744',
  stat: {
    data: ['8.6', '3', '8.7', '6'],
    unit: ['FLYING HOURS', 'NIGHT STOP', 'SOD HOURS', 'SIM INST HRS'],
  },
  statInfoIcon: {
    data: [
      'For April 2024',
      'For April 2024',
      'For April 2024',
      'For April 2024',
    ],
  },
  statInfoIconContent: null,
};
