export const homePageDetails = {
  quickActionLabels: {
    title: 'Quick Action',
    quickAction:
      '/content/dam/my-ai/content_fragment/in/en/navigation-content/my-ai-action-category-list-',
    personalizedNav:
      '/content/dam/my-ai/content_fragment/in/en/navigation-content/my-ai-personalised-General',
  },
  awardsAndAppreciationsLabels: {
    ctaText: 'Appreciate your colleagues',
    title: 'Awards and Appreciations',
    noDataText: 'Every achievement begins with the first step',
  },
  upComingLabels: {
    btnText: 'View More',
    noDataTitle: 'Nothing Upcoming',
    noDataDesc: 'Check back here later for upcoming events and alerts',
    viewMoreIcon: 'chevron_right',
    closeIcon: 'close',
    title: 'Upcoming',
    learningCalendarList: {
      summary: 'Learning courses for your team are awaiting approval.',
      duration: null,
      icon: 'school',
      iconColor: '#DA0E29',
      iconBgColor: 'rgb(218 14 41 / 6%)',
      isExternal: true,
      externalLink: '/content/my-ai/in/en/learning-management.html?tab=2',
      mobilenavlink: 'learning_management/approval_request',
      criticality: 'High',
      name: 'Pending Learning Approvals',
    },
    holidaysList: {
      duration: '21',
      icon: 'mood',
      iconColor: '#DA0E29',
      iconBgColor: 'rgb(218 14 41 / 6%)',
      isExternal: false,
      externalLink: null,
      criticality: 'low',
    },
    teamBirthdaysList: {
      title: 'Birthdays',
      duration: '7',
      iconBgColor: 'rgb(218 14 41 / 6%)',
      isExternal: false,
      externalLink: null,
      icon: 'cake',
      iconColor: '#DA0E29',
      criticality: 'low',
    },
    crewList: {
      noDataTitle: "You're all set!",
      noDataDesc: 'Your alerts and roster updates will appear here',
    },
    crewAlertList: {
      tsa: 60,
      passport: 30,
      visa: 90,
      aep: 60,
      atpl: 60,
      cpl: 60,
      irend: 60,
      cmc: 60,
      medical: 30,
      ca35: 30,
      coid: 30,
      egca: 60,
      frto: 60,
      pmr: 60,
      frro: 60,
      fata: 60,
      expmed: 60,
      yf: 30,
    },
    docNames: {
      coid: 'Company ID Card',
      yf: 'Vaccination - Yellow Fever',
    },
  },
  workPlaceLabels: {
    title: 'Workplace',
    ago: 'ago',
    seeMoreTextBTn: 'See More',
  },
  myBoardLabels: {
    title: 'My Board',
    personaData: [
      {
        persona: 'Pilot',
        cards: [
          {
            id: 'payHours',
            title: 'Block Hours',
            unitColor: null,
            subTitle: 'Completed',
            cardcolor: '#3174E0',
            icon: 'flight_takeoff',
            gradient1Color: 'white',
            gradient2Color: 'white',
            gradient3Color: '#D1E3FF',
            gradient4Color: '#106EFF',
            infoText: 'Per CAE - CM for',
            infoTextTooltip: 'This data is for start_date to end_date',
            infoIcon: 'info',
            zeroDataSubtitle: 'No hours yet',
            zeroDataInfoText: 'Nothing yet',
            dataUnit: 'Hours',
            dataUnitMins: 'min',
            dataUnitHrs: 'hr',
            unitArray: [
              {
                key: 'Flying',
              },
              {
                key: 'SIM hours',
              },
            ],
          },
          {
            id: 'takeoffsLandings',
            title: 'Take Offs / Landings',
            unitColor: '#FF8C00',
            subTitle: null,
            cardcolor: '#FF8C00',
            icon: 'flight',
            gradient1Color: 'white',
            gradient2Color: 'white',
            gradient3Color: '#FFE0BA',
            gradient4Color: '#FF8C00',
            infoText: 'Per PSR for past 90 days',
            infoTextTooltip: 'This data is for start_date to end_date',
            infoIcon: 'info',
            zeroDataSubtitle: 'No Take Offs / Landings',
            zeroDataInfoText: 'Nothing yet',
            dataUnit: 'Total',
            dataUnitMins: 'min',
            dataUnitHrs: 'hr',
            unitArray: [
              {
                key: 'Take offs',
              },
              {
                key: 'Landings',
              },
            ],
          },
          {
            id: 'sodHours',
            title: 'SOD Hours',
            unitColor: '#DA0E29',
            subTitle: 'Completed',
            cardcolor: '#DA0E29',
            icon: 'work_history',
            gradient1Color: 'white',
            gradient2Color: 'white',
            gradient3Color: '#FFC1C9',
            gradient4Color: '#DA0E29',
            infoText: 'Per CAE - CM for',
            infoTextTooltip: 'This data is for start_date to end_date',
            infoIcon: 'info',
            zeroDataSubtitle: 'No SOD Hours',
            zeroDataInfoText: 'Nothing yet',
            dataUnit: 'Hours',
            dataUnitMins: 'min',
            dataUnitHrs: 'hr',
            unitArray: [
              {
                key: 'Intl',
              },
              {
                key: 'Dom',
              },
            ],
          },
          {
            id: 'leaveBalance',
            title: 'Leave Balance',
            unitColor: '#A71EA2',
            subTitle: null,
            cardcolor: '#A71EA2',
            icon: 'calendar_today',
            gradient1Color: 'white',
            gradient2Color: 'white',
            gradient3Color: '#FFCFFD',
            gradient4Color: '#A71EA2',
            infoText: 'Per CAE-CM as of today',
            infoTextTooltip: 'This data was last updated on current_timestamp',
            infoIcon: 'info',
            zeroDataSubtitle: 'No Leaves',
            zeroDataInfoText: 'Nothing yet',
            dataUnit: 'Days',
            dataUnitMins: 'min',
            dataUnitHrs: 'hr',
            unitArray: [
              {
                key: 'PL',
              },
              {
                key: 'CL',
              },
              {
                key: 'SL',
              },
            ],
          },
        ],
      },
      {
        persona: 'Cabin Crew',
        cards: [
          {
            id: 'payHours',
            title: 'Block Hours',
            unitColor: null,
            subTitle: 'Completed',
            cardcolor: '#3174E0',
            icon: 'flight_takeoff',
            gradient1Color: 'white',
            gradient2Color: 'white',
            gradient3Color: '#D1E3FF',
            gradient4Color: '#106EFF',
            infoText: 'Per CAE - CM for',
            infoTextTooltip: 'This data is for start_date to end_date',
            infoIcon: 'info',
            zeroDataSubtitle: 'No hours yet',
            zeroDataInfoText: 'Nothing yet',
            dataUnit: 'Hours',
            dataUnitMins: 'min',
            dataUnitHrs: 'hr',
            unitArray: [
              {
                key: 'CP',
              },
              {
                key: 'FO',
              },
            ],
          },
          {
            id: 'flightDutyPeriod',
            title: 'Night Stops',
            unitColor: null,
            subTitle: 'Completed (Domestic)',
            cardcolor: '#FF8C00',
            icon: 'flight',
            gradient1Color: 'white',
            gradient2Color: 'white',
            gradient3Color: '#FFE0BA',
            gradient4Color: '#FF8C00',
            infoText: 'Per CAE - CM for',
            infoTextTooltip: 'This data is for start_date to end_date',
            infoIcon: 'info',
            zeroDataSubtitle: 'No Night Stops',
            zeroDataInfoText: 'Nothing yet',
            dataUnit: 'Stops',
            dataUnitMins: 'min',
            dataUnitHrs: 'hr',
            unitArray: [
              {
                key: 'Take offs',
              },
              {
                key: 'Landings',
              },
            ],
          },
          {
            id: 'sodHours',
            title: 'SOD Hours',
            unitColor: '#DA0E29',
            subTitle: 'Completed',
            cardcolor: '#DA0E29',
            icon: 'work_history',
            gradient1Color: 'white',
            gradient2Color: 'white',
            gradient3Color: '#FFC1C9',
            gradient4Color: '#DA0E29',
            infoText: 'Per CAE - CM for',
            infoTextTooltip: 'This data is for start_date to end_date',
            infoIcon: 'info',
            zeroDataSubtitle: 'No SOD Hours',
            zeroDataInfoText: 'Nothing yet',
            dataUnit: 'Hours',
            dataUnitMins: 'min',
            dataUnitHrs: 'hr',
            unitArray: [
              {
                key: 'Intl',
              },
              {
                key: 'Dom',
              },
            ],
          },
          {
            id: 'leaveBalance',
            title: 'Leave Balance',
            unitColor: '#A71EA2',
            subTitle: null,
            cardcolor: '#A71EA2',
            icon: 'calendar_today',
            gradient1Color: 'white',
            gradient2Color: 'white',
            gradient3Color: '#FFCFFD',
            gradient4Color: '#A71EA2',
            infoText: 'Per CAE-CM as of today',
            infoTextTooltip: 'This data was last updated on current_timestamp',
            infoIcon: 'info',
            zeroDataSubtitle: 'No Leaves',
            zeroDataInfoText: 'Nothing yet',
            dataUnit: 'Days',
            dataUnitMins: 'min',
            dataUnitHrs: 'hr',
            unitArray: [
              {
                key: 'PL',
              },
              {
                key: 'CL',
              },
              {
                key: 'SL',
              },
            ],
          },
        ],
      },
      {
        persona: 'General',
        cards: [
          {
            id: 'learningHoursCompleted',
            title: 'Learning Time',
            unitColor: null,
            subTitle: 'Spent',
            cardcolor: '#3174E0',
            icon: 'book',
            gradient1Color: 'white',
            gradient2Color: 'white',
            gradient3Color: '#D1E3FF',
            gradient4Color: '#106EFF',
            infoText: null,
            infoTextTooltip: null,
            infoIcon: null,
            zeroDataSubtitle: 'Start your learning',
            zeroDataInfoText: null,
            dataUnit: 'Hours',
            dataUnitMins: 'min',
            dataUnitHrs: 'hr',
            unitArray: [],
          },
          {
            id: 'coursesEnrolled',
            title: 'Courses Enrolled ',
            unitColor: null,
            subTitle: 'Enrolled',
            cardcolor: '#FF8C00',
            icon: 'assignment_add',
            gradient1Color: 'white',
            gradient2Color: 'white',
            gradient3Color: '#FFE0BA',
            gradient4Color: '#FF8C00',
            infoText: null,
            infoTextTooltip: null,
            infoIcon: null,
            zeroDataSubtitle: 'No courses yet',
            zeroDataInfoText: null,
            dataUnit: 'Courses',
            dataUnitMins: 'min',
            dataUnitHrs: 'hr',
            unitArray: [],
          },
          {
            id: 'coursesCompleted',
            title: 'Courses Completed',
            unitColor: null,
            subTitle: 'Completed',
            cardcolor: '#DA0E29',
            icon: 'school',
            gradient1Color: 'white',
            gradient2Color: 'white',
            gradient3Color: '#FFC1C9',
            gradient4Color: '#DA0E29',
            infoText: null,
            infoTextTooltip: null,
            infoIcon: null,
            zeroDataSubtitle: 'Start your learning',
            zeroDataInfoText: null,
            dataUnit: 'Courses',
            dataUnitMins: 'min',
            dataUnitHrs: 'hr',
            unitArray: [],
          },
          {
            id: 'leaveBalance',
            title: 'Leave Balance',
            unitColor: null,
            subTitle: null,
            cardcolor: '#A71EA2',
            icon: 'calendar_today',
            gradient1Color: 'white',
            gradient2Color: 'white',
            gradient3Color: '#FFCFFD',
            gradient4Color: '#A71EA2',
            infoText: null,
            infoTextTooltip: null,
            infoIcon: null,
            zeroDataSubtitle: 'No leaves',
            zeroDataInfoText: null,
            dataUnit: 'Days',
            dataUnitMins: 'min',
            dataUnitHrs: 'hr',
            unitArray: [],
          },
        ],
      },
    ],
    commonMessages: {
      errorText: 'Data not available. Please try again later.',
    },
  },
  bannerLabels: {
    fixedBanner: {
      bannerImage: '/content/dam/my-ai/home-page/banner/Banner1.png',
      bannerImageAltText: 'Banner',
      bannerTitle: null,
      bannerTitleColor: null,
      bannerDesc: null,
      bannerCtaText: null,
      bannerCtaTextColor: null,
      bannerCtaPath: null,
      bannerCtaBgColor: null,
      bannerDescColor: null,
    },
    salutationPersonaDetails: [
      {
        salutationPersona: 'Pilot',
        salutationText: [
          {
            goodMorning: 'Good morning, Captain',
            goodAfternoon: 'Good afternoon, Captain',
            goodEvening: 'Good evening, Captain',
          },
        ],
      },
      {
        salutationPersona: 'Cabin Crew',
        salutationText: [
          {
            goodMorning: 'Good morning,',
            goodAfternoon: 'Good afternoon,',
            goodEvening: 'Good evening,',
          },
        ],
      },
      {
        salutationPersona: 'General',
        salutationText: [
          {
            goodMorning: 'Good morning,',
            goodAfternoon: 'Good afternoon,',
            goodEvening: 'Good evening,',
          },
        ],
      },
    ],
  },
  analyticsInfo: {
    countryCode: 'in',
    countryName: 'India',
    language: 'en',
    pageName: 'myAI | Home',
    pageType: 'AEM',
    server: 'airindia.com',
    siteName: 'myAI',
  },
  roasterLabels: {
    noData: 'No Data',
    viewMore: 'View More',
    viewLess: 'View Less',
    durationText: 'Duration',
    flightNoTxt: 'Flight No.',
    errorTxt: 'No data available. Please try again later',
    noDataTitle: 'No flight',
    noDataDesc: "You don't have any scheduled flights for today and tomorrow",
    title: 'Scheduled Flight',
  },
};

export const pageTitle = 'Home';

export const bannerPageTitle = 'Banner';

export const btnFeedbackNps = 'Feedback';

export const NavigationLabels = {
  navigationData: {
    personalizedNav:
      '/content/dam/my-ai/content_fragment/in/en/navigation-content/my-ai-personalised-General',
    policy:
      '/content/dam/my-ai/content_fragment/in/en/policy-content/my-ai-policy-',
    quickAction:
      '/content/dam/my-ai/content_fragment/in/en/navigation-content/my-ai-action-category-list-',
    benefits:
      '/content/dam/my-ai/content_fragment/in/en/benefit-content/my-ai-benefit-category-list-',
    navigationMenuTitle: 'Apps',
    recent: 'Recent',
    frequentlyUsed: 'Frequently Used',
    allApps: 'All Apps',
    searchForApps: 'Search For Apps',
    backArrowIcon: 'arrow_back',
    searchResultText: 'Search Result',
    noAppsData: 'No results found ',
    noAppsDataMsg: 'Check your spelling or try a different search term',
    eelcPdfPath: '/content/dam/my-ai/content_fragment/in/en/eelc/',
    navCategories: [
      {
        categoryId: 'recent',
        label: 'Recent',
        iconName: null,
        iconColor: null,
        iconBgColor: null,
        actionList: [],
      },
      {
        categoryId: 'frequent-used',
        label: 'Frequently Used',
        iconName: null,
        iconColor: null,
        iconBgColor: null,
        actionList: [],
      },
    ],
  },
  commonData: {
    navigationMenuIcon: 'apps',
    navigationMenuText: 'Apps',
    searchIcon: 'search',
    closeIcon: 'close',
  },
  headerData: {
    profileText: 'View Profile',
    logoutText: 'Logout',
    avatarText: 'Profile',
    logo: '/content/dam/my-ai/logo/myAILogo.svg',
    homeIcon: 'home',
    homeIconText: 'Home',
    desktopHomeLogo: '/content/dam/my-ai/icon/desktop_logo.svg',
    mobileHomeLogo: '/content/dam/my-ai/icon/mobile_logo.svg',
  },
};
