export const labelsLeaveModule = {
  pageTitle: 'LEAVE REQUEST',
  tabDashboard: {
    labelTab: 'Dashboard',
    btnCalendarView: 'Calendar View',
    iconBtnCalendarView: 'calendar_today',
    btnListView: 'List View',
    iconBtnListView: 'list',
    labelSelectRegion: 'Select region',
    iconSelectRegion: 'location_on',
    labelBalance: 'Balance',
    btnApplyLeave: 'Apply Leave',
    iconExpandMore: 'expand_more',
    iconRightArrow: 'chevron_right',
    labelDaysDashboard: 'days',
    labelUpcomingHeading: 'Upcoming Holidays / Leaves',
    labelWeekend: 'Weekend',
    labelApprovedLeave: 'Approved Leave',
    labelPendingLeave: 'Pending Leave',
    labelWorkingWeek: 'Working Week',
    labelHoliday: 'Holiday',
    iconLeftArrow: 'chevron_left',
    labelMore: 'more',
    iconNavigateBefore: 'navigate_before',
    iconNavigateNext: 'navigate_next',
    iconTimelapse: 'timelapse',
    iconMasks: 'masks',
    iconLuggage: 'luggage',
    iconFlag: 'flag',
    iconLogout: 'logout',
    labelHalfDay: 'Half Day',
    labelAllDay: 'All Day',
    labelApproved: 'Approved',
    labelPending: 'Pending',
    labelRejected: 'Rejected',
    labelNoHolidayLeaveList: 'No Holidays / Leaves this month',
  },
  tabNewRequest: {
    labelTab: 'New Request',
    labelFormHeading: 'Leave Application',
    financialYearStartDate: '2024-04-01T00:00:01.000+05:30',
    financialYearEndDate: '2025-03-31T23:59:00.000+05:30',
    labelLeaveType: 'Leave Type',
    labelLeaveBalance: 'Balance',
    labelStartDate: 'Start Date',
    labelEndDate: 'End Date',
    labelDays: 'Days',
    labelLeaveDuration: 'Duration',
    labelReturningToWork: 'Returning to work',
    labelDateOfDelivery: 'Date of Delivery',
    labelEmployeeChildAge: 'Child Age',
    labelDateOfRelocation: 'Date of Relocation',
    labelExpectedDateOfChild: 'Expected Date of Child',
    labelLeaveReason: 'Leave Reason',
    maxCharLengthLeaveReason: '500',
    labelUploadDocument: 'Upload Document',
    btnReset: 'Reset',
    btnSubmit: 'Submit',
    iconArticle: 'article',
    iconClose: 'close',
    labelLeaveReasonPlaceholder: 'Ex. Have some medical urgency',
    labelMandatoryFieldErrorMsg: 'All fields are mandatory',
    labelMandatoryDocumentErrorMsg: 'Supporting document is mandatory',
    labelWrongDocumentTypeOrSizeErrorMsg: 'Wrong document type or size is not under 5000 KB',
    labelDoubleFileExtensionErrorMsg: 'Filename with two extensions is not supported due security restrictions',
    labelFileUploadingMultipleTimesError: 'An error occurred while uploading the document. Please try again later.',
    labelApprovedPendingLeaveCancellationErrorMsg: 'Sorry, you cannot cancel this leave request yet. Please wait until an admin or manager has approved the most recent changes to the leave request.',
    iconDelete: 'delete_outline',
    labelDelete: 'Delete',
    iconView: 'remove_red_eye',
    labelView: 'View',
    labelApproverComment: 'Approver’s Comment',
  },
  uploadDocument: {
    iconCloudUpload: 'cloud_upload',
    labelDragDropFiles: 'Drag & Drop files or ',
    labelBrowse: 'Browse',
    labelDescriptionOne: 'Max file size: 5000 KB, 1 document',
    labelDescriptionTwo: 'Supported formats: JPEG, PNG, PDF',
    iconCloudUploadMobile: 'cloud_upload',
    btnUploadDocument: 'Upload Document',
    labelUploading: 'Uploading | ',
    labelUploaded: 'Uploaded | ',
    labelProgressIndicator: '%',
    iconArticle: 'article',
    iconClose: 'close',
  },
  tabRequestedLeave: {
    labelTab: 'Requested Leave',
    btnPending: 'Pending',
    iconPending: 'timelapse',
    btnApproved: 'Approved',
    iconApproved: 'check',
    btnRejected: 'Rejected',
    iconRejected: 'close',
    labelLeaveType: 'Leave Type',
    labelDateFrom: 'Date From',
    labelDateTo: 'Date To',
    labelRequestDays: 'Request Days',
    labelSubmittedDate: 'Submitted Date',
    labelApprovedDate: 'Approved Date',
    labelRejectedDate: 'Rejected Date',
    btnViewEdit: 'View / Edit',
    btnView: 'View',
    iconArrowDropUp: 'arrow_drop_up',
    iconArrowDropDown: 'arrow_drop_down',
  },
  dialogViewEdit: {
    labelDialogViewEdit: 'View / Edit Leave',
    labelDialogView: 'View Leave',
    labelApprovalStatus: 'Approval Status',
    labelCreatedOn: 'Created on',
    labelUploadedDocuments: 'Uploaded documents',
    iconDelete: 'iconDeleteNewRequest',
    btnDeleteLeave: 'Delete Leave',
    btnCancelEdit: 'Cancel Edit',
    btnSave: 'Save',
  },
  dialogDeleteLeave: {
    labelDialogDeleteLeave: 'Delete leave request',
    iconClose: 'close',
    labelDeleteConfirmation: 'Are you sure you want to delete this leave request? The action cannot be undone',
    btnCancel: 'Cancel',
    btnDelete: 'Yes, delete this leave request',
  },
  analyticsInfo: {
    countryCode: 'in',
    countryName: 'India',
    language: 'en',
    pageName: 'myAI | Leave Request',
    pageType: 'AEM',
    server: 'airindia.com',
    siteName: 'myAI',
  },
};
